In [1]:
import numpy as np

# DataTypes and Attributes

In [2]:
# numpy main data type is ndarray
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from numpy array
import pandas as pd
df = pd.DataFrame(a2) # only convert 2-d array

In [16]:
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


In [17]:
series = pd.Series(a1) # only convert 1-d array

In [18]:
series

0    1
1    2
2    3
dtype: int64

# Creating Array

In [19]:
sample_array = np.array([1,2,3])

In [20]:
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int64')

In [22]:
ones = np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2,3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)

In [29]:
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10,size=(2,5))

In [31]:
random_array

array([[2, 3, 7, 2, 1],
       [6, 2, 9, 0, 7]])

In [32]:
random_array.size

10

In [33]:
random_array.shape

(2, 5)

In [34]:
random_array_2 = np.random.random((2,3))

In [35]:
random_array_2

array([[0.65250025, 0.30251394, 0.10705337],
       [0.85760647, 0.40171256, 0.79214292]])

In [36]:
random_array_2.shape

(2, 3)

In [37]:
random_array_2.size

6

In [38]:
random_array_3 = np.random.rand(2,3)

In [39]:
random_array_3

array([[0.84394701, 0.88831001, 0.39171576],
       [0.74783949, 0.82166498, 0.57168307]])

In [40]:
# Pseudo Random Numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [41]:
random_array_4.shape

(5, 3)

In [42]:
random_array_4.size

15

In [43]:
np.random.seed(seed=0) # it doesnt change random value after that
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

#  3. Viewing Arrays and Matrices

In [44]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a1

array([1, 2, 3])

In [46]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [47]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
a1[0]

np.int64(1)

In [49]:
a2[0]

array([1. , 2. , 3.3])

In [50]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a3[0,1]

array([4, 5, 6])

In [52]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [53]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7],
         [0, 1, 9, 9, 0]],

        [[4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1],
         [4, 9, 8, 1, 1]],

        [[7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4],
         [4, 3, 4, 4, 8]]],


       [[[4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2],
         [4, 2, 0, 3, 2]],

        [[0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4],
         [1, 2, 9, 1, 4]],

        [[6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2],
         [3, 2, 0, 8, 8]]]])

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [55]:
a4[1,1,0,3]

np.int64(9)

In [56]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,4]

array([[[3, 8, 7, 0],
        [7, 5, 1, 1],
        [6, 5, 4, 8]],

       [[5, 3, 2, 2],
        [0, 2, 4, 4],
        [0, 3, 2, 8]]])

## 4. Manipulating and Comparing arrays

### Arithmetic 

In [57]:
a1

array([1, 2, 3])

In [58]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [61]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [62]:
a1 * ones 

array([[1., 2., 3.],
       [1., 2., 3.]])

In [63]:
# How can you reshape a2 to be compatibale with a3?
# Search: How to reshape array
a2_expanded = a2[:,:,None]
a2_expanded * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [64]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [65]:
a2//a1 # remove decimal round values

array([[1., 1., 1.],
       [4., 2., 2.]])

In [66]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [67]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [68]:
a1 % 2

array([1, 0, 1])

In [69]:
a1 / 2

array([0.5, 1. , 1.5])

In [70]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [71]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
### Performing same operation on number of things

In [72]:
listy_list = [1,2,3]
type(listy_list)

list

In [73]:
sum(listy_list)

6

In [74]:
sum(a1)

np.int64(6)

In [75]:
np.sum(a1)

np.int64(6)

# Use python's method on python datatypes and use 
# Numpy's methods on NumPy arrays

In [82]:
# create a massive numpy array

massive_array = np.random.random(100000)
massive_array.size

100000

In [83]:
massive_array[:10]

array([0.38849579, 0.17518866, 0.07733528, 0.87224364, 0.83140254,
       0.55176048, 0.80888769, 0.11902725, 0.73908009, 0.32196028])

In [85]:
%timeit sum(massive_array) # Python sum method
%timeit np.sum(massive_array) # NumPy sum method

4.55 ms ± 113 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20.7 μs ± 230 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [86]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [87]:
np.mean(a2)

np.float64(3.6333333333333333)

In [88]:
np.max(a2)

np.float64(6.5)

In [89]:
np.min(a2)

np.float64(1.0)

In [92]:
# standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

np.float64(1.8226964152656422)

In [93]:
# variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

np.float64(3.3222222222222224)

In [94]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

np.float64(1.8226964152656422)