In [1]:
import numpy as np

# DataTypes and Attributes

In [2]:
# numpy main data type is ndarray
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [21]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [22]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [23]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [24]:
a1.shape

(3,)

In [25]:
a2.shape

(2, 3)

In [26]:
a3.shape

(2, 3, 3)

In [27]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [28]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [29]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [30]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [46]:
# Create a DataFrame from numpy array
import pandas as pd
df = pd.DataFrame(a2) # only convert 2-d array

In [47]:
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


In [48]:
series = pd.Series(a1) # only convert 1-d array

In [49]:
series

0    1
1    2
2    3
dtype: int64