In [1]:
import numpy as np

# DataTypes and Attributes

In [2]:
# numpy main data type is ndarray
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from numpy array
import pandas as pd
df = pd.DataFrame(a2) # only convert 2-d array

In [16]:
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


In [17]:
series = pd.Series(a1) # only convert 1-d array

In [18]:
series

0    1
1    2
2    3
dtype: int64

# Creating Array

In [19]:
sample_array = np.array([1,2,3])

In [20]:
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int64')

In [22]:
ones = np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2,3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)

In [29]:
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10,size=(2,5))

In [31]:
random_array

array([[0, 5, 8, 1, 9],
       [1, 6, 8, 5, 0]])

In [32]:
random_array.size

10

In [33]:
random_array.shape

(2, 5)

In [34]:
random_array_2 = np.random.random((2,3))

In [35]:
random_array_2

array([[0.39345474, 0.19765744, 0.37491439],
       [0.32496653, 0.57114864, 0.60072671]])

In [36]:
random_array_2.shape

(2, 3)

In [37]:
random_array_2.size

6

In [38]:
random_array_3 = np.random.rand(2,3)

In [39]:
random_array_3

array([[0.74413557, 0.26943434, 0.02115331],
       [0.40462107, 0.11958373, 0.99518199]])

In [55]:
# Pseudo Random Numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [56]:
random_array_4.shape

(5, 3)

In [57]:
random_array_4.size

15

In [58]:
np.random.seed(seed=0) # it doesnt change random value after that
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

#  3. Viewing Arrays and Matrices

In [59]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1

array([1, 2, 3])

In [61]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [62]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
a1[0]

np.int64(1)

In [65]:
a2[0]

array([1. , 2. , 3.3])

In [66]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a3[0,1]

array([4, 5, 6])

In [71]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [83]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 8, 2, 8, 4],
         [3, 0, 4, 3, 6],
         [9, 8, 0, 8, 5],
         [9, 0, 9, 6, 5]],

        [[3, 1, 8, 0, 4],
         [9, 6, 5, 7, 8],
         [8, 9, 2, 8, 6],
         [6, 9, 1, 6, 8]],

        [[8, 3, 2, 3, 6],
         [3, 6, 5, 7, 0],
         [8, 4, 6, 5, 8],
         [2, 3, 9, 7, 5]]],


       [[[3, 4, 5, 3, 3],
         [7, 9, 9, 9, 7],
         [3, 2, 3, 9, 7],
         [7, 5, 1, 2, 2]],

        [[8, 1, 5, 8, 4],
         [0, 2, 5, 5, 0],
         [8, 1, 1, 0, 3],
         [8, 8, 4, 4, 0]],

        [[9, 3, 7, 3, 2],
         [1, 1, 2, 1, 4],
         [2, 5, 5, 5, 2],
         [5, 7, 7, 6, 1]]]])

In [86]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [89]:
a4[1,1,0,3]

np.int64(8)

In [98]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,4]

array([[[4, 6, 5, 5],
        [4, 8, 6, 8],
        [6, 0, 8, 5]],

       [[3, 7, 7, 2],
        [4, 0, 3, 0],
        [2, 4, 2, 1]]])

## 4. Manipulating and Comparing arrays

### Arithmetic 

In [99]:
a1

array([1, 2, 3])

In [100]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [101]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [102]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [103]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [104]:
a1 * ones 

array([[1., 2., 3.],
       [1., 2., 3.]])

In [106]:
# How can you reshape a2 to be compatibale with a3?
# Search: How to reshape array
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [109]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [110]:
a2//a1 # remove decimal round values

array([[1., 1., 1.],
       [4., 2., 2.]])

In [111]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [112]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [113]:
a1 % 2

array([1, 0, 1])

In [114]:
a1 / 2

array([0.5, 1. , 1.5])

In [115]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [116]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])